import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { ProductList } from '../component/product'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Ecommerce Stripe Boilerplate</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Ecommerce Stripe Boilerplate</h1>

        <p className={styles.description}>
          This is a simple ecommerce boilerplate with stripe only
        </p>

        <ul className={styles.grid}>
          <ProductList />
        </ul>
      </main>

      <footer className={styles.footer}>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
